name : my first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hellow world"
      - name: Print goodbye
        run: echo "Good Bye"
      - name: Print multipe lines
        run: |
          echo "line 1"
          echo "line 2"
